<?php

namespace App\DataFixtures;

use App\Entity\Location;
use App\Entity\Type;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpClient\HttpClient;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $client = HttpClient::create();

        $titles = [
            "Anatole France élémentaire",
            "Association Formation Professionnelle des Adultes (AFPA)",
            "Basket Park",
            "Bibliothèque - discothèque municipale",
            "Bois de la Garenne",
            "Bois du Château de la Solitude",
            "Canisette Alliés",
            "Canisette Blum",
            "Canisette Bois des Vallées",
            "Canisette CES",
            "Canisette Fidel",
            "Canisette Fourcade",
            "Canisette Garenne",
            "Canisette Laennec",
            "Canisette Mairie",
            "Canisette Malot",
            "Canisette Pergaud",
            "Canisette Sertillanges",
            "Canisette STNA",
            "Canisette Thomas",
            "CAT Les Robinsons",
            "Centre administratif municipal",
            "Centre municipal de Santé Robert-Fasquelle",
            "Cimetière",
            "Cinéma Gerard Philipe",
            "Cité de l’enfance",
            "Collège Claude Nicolas Ledoux",
            "Collège Romain Rolland",
            "Complexe sportif Joliot-Curie",
            "Complexe sportif Louis-Hachette",
            "Déchetterie",
            "Ecole maternelle de la Ferme",
            "Ecole Raymond Aumont",
            "Eglise Saint Jean Baptiste",
            "Eglise Sainte-Marie-Magdeleine",
            "Emploi Hauts-de-Bièvre",
            "Espace Brossolette",
            "Espace Omnisport",
            "Espace Péri",
            "Etang Colbert",
            "Expoville",
            "François Peatrik",
            "François Peatrik",
            "François Peatrik élémentaire",
            "François Peatrik maternelle",
            "Free Park",
            "Groupe scolaire Jean Jaurès",
            "Groupe scolaire Louis Pergaud",
            "Gymnase Anatole France",
            "Gymnase du Pierrier",
            "Gymnase François Peatrik",
            "Gymnase Henri Wallon",
            "Halte Garderie : L'île aux trésors",
            "Henri Wallon",
            "Henri Wallon",
            "Henri Wallon élémentaire",
            "Henri Wallon maternelle",
            "Hôpital Marie Lannelongue",
            "Hôtel de Ville",
            "Jardin de Robinson",
            "Jardin de Sertillanges",
            "Jardins de L’Hôtel de Ville",
            "Jardins Familiaux",
            "Jean Jaurès",
            "Joliot-Curie",
            "Joliot-Curie",
            "Joliot-Curie élémentaire",
            "Joliot-Curie maternelle",
            "L'Ile aux Bambins",
            "L'Orangerie",
            "La Ferme",
            "La Ferme",
            "La pouponnière, Aide Sociale À l'Enfance",
            "Le Club",
            "Le Grand Large",
            "Le Pierrier",
            "Le Relais d’Assistantes Parentales",
            "Les Dauphins",
            "Les Etoiles de Mer",
            "Les Loups de Mer",
            "Les P'tits Mousses",
            "Les P'tits Pirates",
            "Les petits mariniers (BABILOU)",
            "Les Poissons-clowns",
            "Lieu d'accueil parents-enfants (LAEP)",
            "Louis Hachette",
            "Louis Hachette",
            "Louis Hachette",
            "Louis Hachette élémentaire",
            "Louis Hachette maternelle",
            "Louis Pergaud",
            "Louis Pergaud",
            "Lycée Montesquieu",
            "L’Ile aux trésors",
            "Maison de la Musique et de la Danse",
            "Maison des Entreprises et de l’Emploi des Hauts-de-Bièvre",
            "Marché",
            "Notaire",
            "P.M.I (Protection Maternelle et Infantile)- Centre de planning familial",
            "Parc de la Vallée aux Loups",
            "Parc des Sports",
            "Parc du Moulin Fidel",
            "Parc Henri Sellier",
            "Piscine du Hameau",
            "Police Municipale",
            "Police Nationale",
            "Poste de Plessis les Halles",
            "Poste du Cœur de Ville",
            "Promenade de la Cité jardins",
            "Propriété du  Moulin Fidel",
            "Relais Assistante Maternelle",
            "Résidence  d’Artagnan",
            "Résidence  Paulette Spiess",
            "Résidence Henri Sellier",
            "Salle de Musculation",
            "Salle des Fêtes",
            "Sapeurs Pompiers",
            "Sécurité sociale",
            "Sertillanges",
            "Service de l’Urbanisme",
            "Services Techniques",
            "Skate Park",
            "Tennis club",
            "Théâtre du Coteau"
        ];

        $addresslist = [
            "5 Bis rue de la ferme, 92350 Le Plessis-Robinson",
            "4 rue de Sceaux, 92350 Le Plessis-Robinson",
            "Allée Robert-Debré, 92350 Le Plessis-Robinson",
            "2, rue André-Le Nôtre, 92350 Le Plessis-Robinson",
            "Bois de la Garenne, 92350 Le Plessis-Robinson",
            "Bois du Château de la Solitude, 92350 Le Plessis-Robinson",
            "Place des Alliés, 92350 Le Plessis-Robinson",
            "Avenue Léon Blum, 92350 Le Plessis-Robinson",
            "Bois des Vallées, 92350 Le Plessis-Robinson",
            "Place Woking, 92350 Le Plessis-Robinson",
            "Rue du Moulin Fidel, 92350 Le Plessis-Robinson",
            "Rue Fernand Fourcade, 92350 Le Plessis-Robinson",
            "Rue de la Garenne, 92350 Le Plessis-Robinson",
            "Rue du Loup Pendu, 92350 Le Plessis-Robinson",
            "Chemin des Ecoles, 92350 Le Plessis-Robinson",
            "Avenue Florian Square Malot, 92350 Le Plessis-Robinson",
            "Rue Louis Pergaud, 92350 Le Plessis-Robinson",
            "30 avenue du Général Leclerc, 92350 Le Plessis-Robinson",
            "Avenue du Plessis, 92350 Le Plessis-Robinson",
            "Avenue Albert Thomas, 92350 Le Plessis-Robinson",
            "29 rue Paul-Rivet, 92350 Le Plessis-Robinson",
            "3, place de la Mairie, 92350 Le Plessis-Robinson",
            "1, villa des Camélias, 92350 Le Plessis-Robinson",
            "26, avenue Edouard-Herriot, 92350 Le Plessis-Robinson",
            "2, rue André-Le Nôtre92350 Le Plessis-Robinson",
            "5 avenue du Général Leclerc, 92350 Le Plessis-Robinson",
            "Rue Claude Nicolas Ledoux, 92350 Le Plessis-Robinson",
            "Avenue Edouard-Herriot, 92350 Le Plessis-Robinson",
            "Allée Robert-Debré, 92350 Le Plessis-Robinson",
            "Avenue Paul Langevin, 92350 Le Plessis-Robinson",
            "Avenue Georges-Pompidou, 91370 Verrières-le-Buisson",
            "5 rue de la Ferme, 92350 Le Plessis-Robinson",
            "3 allée Robert Debré, 92350 Le Plessis-Robinson",
            "Place de la Mairie, 92350 Le Plessis-Robinson",
            "Rue André-Le-Nôtre, 92350 Le Plessis-Robinson",
            "42, avenue Aristide Briand, 92350 Le Plessis-Robinson",
            "2, rue Pierre Brossolette, 92350 Le Plessis-Robinson",
            "Avenue Edouard-Herriot Place Woking, 92350 Le Plessis-Robinson",
            "Avenue Gabriel-Péri, 92350 Le Plessis-Robinson",
            "rue du Tour de l'Etang, 92350 Le Plessis-Robinson",
            "8 avenue de la Libération, 92350 Le Plessis-Robinson",
            "Place de l’Auditorium, 92350 Le Plessis-Robinson",
            "Place de l'auditorium, 92350 Le Plessis-Robinson",
            "Place de l’Auditorium, 92350 Le Plessis-Robinson",
            "Place de l’Auditorium, 92350 Le Plessis-Robinson",
            "Rue du Loup Pendu, 92350 Le Plessis-Robinson",
            "9, rue des Suisses, 92350 Le Plessis-Robinson",
            "4, rue Louis-Pergaud, 92350 Le Plessis-Robinson",
            "Rue de la Ferme, 92350 Le Plessis-Robinson",
            "10, rue Louis-Pergaud, 92350 Le Plessis-Robinson",
            "Rue François Peatrik, 92350 Le Plessis-Robinson",
            "Rue du Capitaine Facq, 92350 Le Plessis-Robinson",
            "9, rue Pierre-d’Artagnan, 92350 Le Plessis-Robinson",
            "21 rue du Capitaine Facq, 92350 Le Plessis-Robinson",
            "21, rue du Capitaine Facq, 92350 Le Plessis-Robinson",
            "21, rue du Capitaine-Facq, 92350 Le Plessis-Robinson",
            "21, rue du Capitaine-Facq, 92350 Le Plessis-Robinson",
            "133 avenue de la Résistance, 92350 Le Plessis-Robinson",
            "3, place de la Mairie, 92350 Le Plessis-Robinson",
            "Place des Alliés, 92350 Le Plessis-Robinson",
            "avenue du Général Leclerc, 92350 Le Plessis-Robinson",
            "Parc du 11 novembre 1918, 92350 Le Plessis-Robinson",
            "Avenue Pierre Brossolette, 92350 Le Plessis-Robinson",
            "9 rue des Suisses, 92350 Le Plessis-Robinson",
            "2, allée Robert-Debré, 92350 Le Plessis-Robinson",
            "2, allée Robert-Debré, 92350 Le Plessis-Robinson",
            "3, allée Robert Debré, 92350 Le Plessis-Robinson",
            "3, allée Robert Debré, 92350 Le Plessis-Robinson",
            "3 rue de l’Orangerie, 92350 Le Plessis-Robinson",
            "Rue le la Mairie, 92350 Le Plessis-Robinson",
            "5, rue de l'Orangerie, 92350 Le Plessis-Robinson",
            "3, rue de l'Orangerie, 92350 Le Plessis-Robinson",
            "5 avenue du Général Leclerc, 92350 Le Plessis-Robinson",
            "1, Place Henri-Barbusse, 92350 Le Plessis-Robinson",
            "1, Place de la Résistance, 92350 Le Plessis-Robinson",
            "10, rue Louis-Pergaud, , 92350 Le Plessis-Robinson",
            "4-6 rue de la Ferme, 92350 Le Plessis-Robinson",
            "3 rue Auguste-Rodin, 92350 Le Plessis-Robinson",
            "20/22 avenue de la Libération, 92350 Le Plessis-Robinson",
            "9, avenue Roger Salengro, 92350 CHATENAY-MALABRY",
            "9, Chemin de la Côte Sainte Catherine, 92350 Le Plessis-Robinson",
            "34 rue Edmond-About, 92350 Le Plessis-Robinson",
            "81/83 avenue Edouard Herriot, 92350 Le Plessis-Robinson",
            "6 rue de la Ferme, 92350 Le Plessis-Robinson",
            "4-6, rue de la Ferme, 92350 Le Plessis-Robinson",
            "Place des Déportés et Internés de la Résistance, 92350 Le Plessis-Robinson",
            "Place des déportes et Internés de la Résistance, 92350 Le Plessis-Robinson",
            "Place des déportes et Internés de la Résistance, 92350 Le Plessis-Robinson",
            "Place des Déportés et Internés de la Résistance, 92350 Le Plessis-Robinson",
            "Place des Déportés et Internés de la Résistance, 92350 Le Plessis-Robinson",
            "4, rue Louis Pergaud, 92350 Le Plessis-Robinson",
            "4, rue Louis-Pergaud, 92350 Le Plessis-Robinson",
            "21, rue du Capitaine Facq, 92350 Le Plessis-Robinson",
            "9 rue Pierre-d’Artagnan",
            "70, rue du Moulin Fidel, 92350 Le Plessis-Robinson",
            "42, avenue Aristide-Briand, 92160 Antony",
            "Place de la Libération, 92350 Le Plessis-Robinson",
            "30, avenue Charles de Gaulle, 92350 Le Plessis-Robinson",
            "Villa des Hortensias, 92350 Le Plessis-Robinson",
            "Parc de la Vallée aux Loups, 92350 Le Plessis-Robinson",
            "Avenue Paul-Langevin et avenue Galilée, 92350 Le Plessis-Robinson",
            "Rue du Moulin Fidel, 92350 Le Plessis-Robinson",
            "Parc Henri Sellier, 92350 Le Plessis-Robinson",
            "5, rue Blaise Pascal, 92350 Le Plessis-Robinson",
            "Cour de l'Hôtel de Ville, 92350 Le Plessis-Robinson",
            "3 bis, rue Pierre d'Artagnan, 92350 Le Plessis-Robinson",
            "4, avenue de la Libération, 92350 Le Plessis-Robinson",
            "8 Grande Rue, 92350 Le Plessis-Robinson",
            "Promenade des berges, 92350 Le Plessis-Robinson",
            "Rue du Moulin Fidel, 92350 Le Plessis-Robinson",
            "4-6, rue de la Ferme, 92350 Le Plessis-Robinson",
            "1, square Jacques-Ange-Gabriel, 92350 Le Plessis-Robinson",
            "23, rue de la Raye Tortue, 92350 Le Plessis-Robinson",
            "123, rue de Malabry, 92350 Le Plessis-Robinson",
            "Rue Louis-Pergaud, 92350 Le Plessis-Robinson",
            "14, avenue Galilée, 92350 Le Plessis-Robinson",
            "287, avenue du Général de Gaulle, 92350 CLAMART",
            "5, rue Pierre d’Artagnan, 92350 Le Plessis-Robinson",
            "30, avenue du Général-Leclerc, 92350 Le Plessis-Robinson",
            "14, avenue Galilée, 92350 Le Plessis-Robinson",
            "14, avenue Galilée, 92350 Le Plessis-Robinson",
            "9 avenue Paul-Langevin, 92350 Le Plessis-Robinson",
            "Avenue Paul-Langevin et avenue Galilée B.P. 3492350 Le Plessis-Robinson",
            "10, rue Louis-Pergaud, 92350 Le Plessis-Robinson"
        ];

        $categories = ['Services municipaux',
            'Halte Garderie',
            'Crèche', 'Enfance',
            'Collèges', 'Lycée',
            'Pratique / infos utiles',
            'Equipements culturels',
            'Emploi & insertion',
            'Installations sportives',
            'Hopitaux',
            'Résidence de personnes âgées',
            'Parcs et jardins',
            'Lieux de culte',
            'Accueil périscolaire maternel',
            'Ecole élémentaire',
            'Ecole maternelle',
            'Ecole maternelle et élémentaire',
            'Centre de loisirs maternel',
            'Centre de loisirs primaire',
            'Environnement'
        ];

        $categoriesrepeated = [
                'Ecole élémentaire',
                'Emploi & insertion',
                'Installations sportives',
                'Equipements culturels',
                'Parcs et jardins',
                'Parcs et jardins',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Environnement',
                'Emploi & insertion',
                'Services municipaux',
                'Services municipaux',
                'Services municipaux',
                'Equipements culturels',
                'Enfance',
                'Collèges',
                'Collèges',
                'Installations sportives',
                'Installations sportives',
                'Environnement',
                'Ecole maternelle',
                'Ecole maternelle et élémentaire',
                'Lieux de culte',
                'Lieux de culte',
                'Emploi & insertion',
                'Installations sportives',
                'Installations sportives',
                'Installations sportives',
                'Parcs et jardins',
                'Equipements culturels',
                'Accueil périscolaire maternel',
                'Centre de loisirs maternel',
                'Ecole élémentaire',
                'Ecole maternelle',
                'Installations sportives',
                'Ecole maternelle et élémentaire',
                'Ecole maternelle et élémentaire',
                'Installations sportives',
                'Installations sportives',
                'Installations sportives',
                'Installations sportives',
                'Halte Garderie',
                'Accueil périscolaire maternel',
                'Centre de loisirs maternel',
                'Ecole élémentaire',
                'Ecole maternelle',
                'Hopitaux',
                'Services municipaux',
                'Parcs et jardins',
                'Parcs et jardins',
                'Parcs et jardins',
                'Parcs et jardins',
                'Accueil périscolaire maternel',
                'Accueil périscolaire maternel',
                'Centre de loisirs maternel',
                'Ecole élémentaire',
                'Ecole maternelle',
                'Crèche',
                'Equipements culturels',
                'Accueil périscolaire maternel',
                'Centre de loisirs maternel',
                'Enfance',
                'Services municipaux',
                'Services municipaux',
                'Centre de loisirs primaire',
                'Enfance',
                'Crèche',
                'Crèche',
                'Crèche',
                'Crèche',
                'Crèche',
                'Crèche',
                'Crèche',
                'Enfance',
                'Accueil périscolaire maternel',
                'Centre de loisirs maternel',
                'Centre de loisirs primaire',
                'Ecole élémentaire',
                'Ecole maternelle',
                'Accueil périscolaire maternel',
                'Centre de loisirs maternel',
                'Lycée',
                'Crèche',
                'Equipements culturels',
                'Emploi & insertion',
                'Pratique / infos utiles',
                'Pratique / infos utiles',
                'Enfance',
                'Parcs et jardins',
                'Installations sportives',
                'Parcs et jardins',
                'Parcs et jardins',
                'Installations sportives',
                'Services municipaux',
                'Pratique / infos utiles',
                'Pratique / infos utiles',
                'Pratique / infos utiles',
                'Parcs et jardins',
                'Equipements culturels',
                'Enfance',
                'Résidence de personnes âgées',
                'Résidence de personnes âgées',
                'Résidence de personnes âgées',
                'Installations sportives',
                'Services municipaux',
                'Pratique / infos utiles',
                'Pratique / infos utiles',
                'Centre de loisirs primaire',
                'Services municipaux',
                'Services municipaux',
                'Installations sportives',
                'Installations sportives',
                'Equipements culturels'
        ];

        for ($i = 1; $i <= 21; $i++){
            $type = new Type();
            $type->setTypeName($categories[$i-1]);
            $manager->persist($type);
        }
        $manager->flush();

        for ($i = 1; $i <= 124; $i++){
            $location = new Location();
            $location->setName($titles[$i-1]);
            $location->setAddress($addresslist[$i-1]);
            if (is_numeric($addresslist[$i-1][0])) {
                $typeUrl = 'housenumber';
            } else {
                $typeUrl = 'street';
            }
            $response = $client->request('GET', 'https://api.geoapify.com/v1/geocode/search?text=' . urlencode($addresslist[$i-1]) . '&apiKey=977dfc7340ca46af8c75b8b6928c4a7a' );
            $response = $response->toArray();
            if (array_key_exists(0, ($response['features']))) {
                $response = $response['features'][0]['properties'];
                $location->setLatitude($response['lat']);
                $location->setLongitude($response['lon']);
            } else {
                $location->setLatitude(0);
                $location->setLongitude(0);
            }
            $location->setDescription('Ceci est une description de ' . $titles[$i-1]);
            $location->setImage('Image_url');
            $type = $manager->getRepository(Type::class)->findOneBy(['type_name' => $categoriesrepeated[$i-1]]);
            $location->addType($type);
            $manager->persist($location);
        }
        $manager->flush();
    }
}
